name: "Install Dependencies"
description: "Action to build the project dependencies using uv"

inputs:
  python_version:
    required: true
    type: string
    default: "3.11.6"
  uv_version:
    required: true
    type: string
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}
        cache: "pip"

    - name: Install Uv
      run: |
        curl -sSL https://path.to/uv/install.sh | bash -s -- --version ${{ inputs.uv_version }}
        echo "${HOME}/.local/bin" >> $GITHUB_PATH

    - name: Install Dependencies
      run: uv sync
      shell: bash
